services:
  grafana:
    platform: 'linux/amd64'
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-13.1.0}
        development: ${DEVELOPMENT:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    volumes:
      - ./dist:/var/lib/grafana/plugins/vonage-status-panel-react

    environment:
      GF_LOG_LEVEL: info
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
